import {spawn} from 'node:child_process';import {once} from 'node:events';
import {createRequire} from 'node:module';import {mkdir} from 'node:fs/promises';import assert from 'node:assert/strict';
const require=createRequire(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES ? process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/package.json' : import.meta.url);const {chromium}=require('playwright');
let server;if(process.env.AUTO_SERVE||process.argv.includes('--serve')){server=spawn(process.execPath,['tools/serve.mjs'],{stdio:['ignore','pipe','pipe']});await Promise.race([once(server.stdout,'data'),once(server,'exit').then(()=>{throw Error('preview server exited')})]);}
const browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_EXECUTABLE_PATH||undefined,args:process.env.CHROMIUM_EXECUTABLE_PATH?['--no-sandbox','--disable-gpu']:[]});
try{const page=await browser.newPage({viewport:{width:393,height:852}});const errors=[];page.on('pageerror',e=>errors.push(e.message));await mkdir('artifacts',{recursive:true});await page.goto('http://127.0.0.1:4173');await page.evaluate(()=>localStorage.clear());await page.reload();
const snap=async name=>{await page.screenshot({path:`artifacts/${name}.png`,fullPage:true});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true)};
await snap('01-ready');assert.equal(await page.locator('#ready').isVisible(),true);assert.equal(await page.locator('.game-art img').evaluateAll(imgs=>imgs.every(i=>i.complete&&i.naturalWidth>0)),true);
await page.locator('#start').click();await page.locator('#hit').click();assert.equal(await page.locator('#progress').textContent(),'10 / 180');assert.equal(await page.locator('#round-actions').textContent(),'1');await snap('02-battle');await page.reload();assert.equal(await page.locator('#rest').isVisible(),true);assert.equal(await page.locator('#progress').textContent(),'10 / 180');await snap('03-rest');await page.locator('#resume').click();for(let i=0;i<3;i++)await page.locator('#hit').click();assert.equal(await page.locator('#stageClear').isVisible(),true);await snap('04-stage');
await page.locator('#end-stage').click();await page.locator('#advance').click();assert.equal(await page.locator('#round-actions').textContent(),'0');assert.equal(await page.locator('#progress').textContent(),'40 / 180');
for(let i=0;i<6;i++)await page.locator('#hit').click();await page.locator('#advance').click();for(let i=0;i<8;i++)await page.locator('#hit').click();assert.equal(await page.locator('#win').isVisible(),true);assert.equal(await page.locator('#win-summary').textContent(),'总计 18 次 · 2 轮完成');assert.equal(await page.locator('#progress').textContent(),'180 / 180');await snap('05-win');await page.locator('#return').click();assert.equal(await page.locator('#overview').isVisible(),true);await page.locator('#enter').click();assert.equal(await page.locator('#win').isVisible(),true);
// An IO boundary failure must neither count nor show attack success.
await page.evaluate(()=>localStorage.clear());await page.reload();await page.locator('#start').click();await page.evaluate(()=>{Storage.prototype.setItem=function(){throw Error('disk full')}});await page.locator('#hit').click();assert.equal(await page.locator('#progress').textContent(),'0 / 180');assert.equal(await page.locator('#damage-fx').textContent(),'');assert.equal(await page.locator('#save-failure').isVisible(),true);assert.equal(await page.locator('#hit').isDisabled(),true);assert.equal(await page.locator('#retry').evaluate(e=>{const b=e.getBoundingClientRect();return b.top>=0&&b.bottom<=innerHeight}),true);await snap('06-save-failure');assert.deepEqual(errors,[]);console.log('Browser: all five states, reload, new round, full win, resources, mobile width and failed-save feedback PASS');
}finally{await browser.close();server?.kill()}
