import {spawn} from 'node:child_process';
import {once} from 'node:events';
import {mkdir} from 'node:fs/promises';
import assert from 'node:assert/strict';
import {chromium} from 'playwright';
const server=spawn(process.execPath,['tools/serve.mjs'],{stdio:['ignore','pipe','pipe']});
let browser;
try{
 await Promise.race([once(server.stdout,'data'),once(server,'exit').then(()=>{throw Error('preview server exited')})]);
 browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_EXECUTABLE_PATH});
 const page=await browser.newPage({viewport:{width:393,height:852}}),errors=[];
 page.on('pageerror',error=>errors.push(error.message));
 await page.goto('http://127.0.0.1:4173');
 await page.locator('#start').click();await page.locator('#hit').click();
 await page.locator('#home').click();await page.locator('#enter-knee').click();
 assert.equal(await page.locator('#title').textContent(),'踏光栈道');
 assert.equal(await page.locator('#progress').textContent(),'0 / 220');
 assert.equal(await page.locator('#scene').isVisible(),false);
 assert.equal(await page.locator('#standing-steps .path-step').count(),22);
 await mkdir('artifacts',{recursive:true});
 const snap=async name=>{await page.screenshot({path:`artifacts/${name}.png`,fullPage:true});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true)};
 await snap('standing-ready');await page.locator('#start').click();
 for(let i=0;i<6;i++)await page.locator('#hit').click();
 assert.equal(await page.locator('#standing-steps .lit').count(),6);
 assert.match(await page.locator('#next-stage').textContent(),/侧抬腿/);await snap('standing-transition');
 await page.locator('#advance').click();
 assert.equal(await page.locator('#profile').inputValue(),'legraise.side');
 assert.equal(await page.locator('#round-actions').textContent(),'0');
 for(let i=0;i<3;i++)await page.locator('#hit').click();
 await page.reload();assert.equal(await page.locator('#progress').textContent(),'10 / 180');
 await page.locator('#home').click();await page.locator('#enter-knee').click();
 assert.equal(await page.locator('#rest').isVisible(),true);assert.equal(await page.locator('#progress').textContent(),'90 / 220');
 await page.locator('#resume').click();for(let i=0;i<5;i++)await page.locator('#hit').click();
 await page.locator('#advance').click();assert.equal(await page.locator('#profile').inputValue(),'kneeraise.standing');
 for(let i=0;i<8;i++)await page.locator('#hit').click();
 assert.equal(await page.locator('#win').isVisible(),true);assert.equal(await page.locator('#progress').textContent(),'220 / 220');
 assert.equal(await page.locator('#standing-steps .lit').count(),22);
 assert.equal(await page.locator('#win-summary').textContent(),'总计 22 次 · 3 轮完成');await snap('standing-win');
 await page.locator('#return').click();await page.locator('#enter').click();assert.equal(await page.locator('#progress').textContent(),'10 / 180');
 assert.deepEqual(errors,[]);
 console.log('Standing browser PASS: three stages, exercise transitions, 22 lit steps, separate saves, reload, mobile width, no JS errors.');
}finally{await browser?.close();server.kill();}
