import test from 'node:test';import assert from 'node:assert/strict';
import {createRun,reduce} from '../preview/lib/core.js';import {view,feedback} from '../preview/lib/ui.js';
const start={type:'startRound',roundId:'r1',source:'button',exerciseProfileId:'pushup.wall'};
const hit=(s,id)=>reduce(s,{type:'action',eventId:id,roundId:s.currentRoundId,inputEpoch:s.inputEpoch,source:'button',exerciseProfileId:'pushup.wall'});
test('ready shows cumulative progress but current round counts reset on a new round',()=>{let s=reduce(createRun('x'),start);s=hit(s,'1');s=reduce(s,{type:'endRound'});let v=view(s);assert.equal(v.screen,'ready');assert.equal(v.damage,10);s=reduce(s,{...start,roundId:'r2'});v=view(s);assert.equal(v.roundActions,0);assert.equal(v.roundDamage,0);assert.equal(v.damage,10)});
test('paused and stage clear each expose only their appropriate primary action',()=>{let s=reduce(createRun('x'),start);s=hit(s,'1');const paused=view(reduce(s,{type:'pause'}));assert.equal(paused.screen,'rest');assert.equal(paused.primary,'resume');for(let i=2;i<=4;i++)s=hit(s,''+i);const v=view(s);assert.equal(v.screen,'stageClear');assert.equal(v.primary,'advance');assert.equal(v.roundActions,4);assert.equal(v.roundDamage,40);assert.equal(v.nextStage,'双生护盾')});
test('completion uses sealed last round and actual history',()=>{let s=reduce(createRun('x'),start);let i=0;while(s.phase!=='complete'){if(s.phase==='stageClear')s=reduce(s,{type:'advanceStage'});s=hit(s,''+(++i));}const v=view(s);assert.equal(v.screen,'win');assert.equal(v.primary,'none');assert.equal(v.roundActions,18);assert.equal(v.roundDamage,180);assert.equal(v.damage,180);assert.equal(v.roundCount,1)});
test('only durable state changes produce feedback, capped damage is used',()=>{const a=reduce(createRun('x'),start);assert.deepEqual(feedback(a,a),{damage:0,stageClear:false,win:false});const b=hit(a,'1');assert.equal(feedback(a,b).damage,10);let s=b;for(let i=2;i<=3;i++)s=hit(s,''+i);const c=hit(s,'4');assert.deepEqual(feedback(s,c),{damage:10,stageClear:true,win:false})});
test('current input source distinguishes camera actions from button simulations',()=>{let s=createRun('camera');s=reduce(s,{type:'startRound',roundId:'r',source:'camera',exerciseProfileId:'pushup.wall'});assert.equal(view(s).sourceLabel,'摄像头识别');let b=createRun('button');b=reduce(b,{type:'startRound',roundId:'r',source:'button',exerciseProfileId:'pushup.wall'});assert.equal(view(b).sourceLabel,'按钮模拟')});
