import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import {readFileSync} from 'node:fs';import {createRequire} from 'node:module';
const require=createRequire(import.meta.url);
function page(fail=false,detector=null){let config;const data=new Map();const wx={getStorageSync:k=>data.get(k),setStorageSync:(k,v)=>{if(fail||config.__page?.failWrites)throw Error('full');data.set(k,v)},showToast(){},createCameraContext(){return {onCameraFrame(cb){config.__page.testFrame=cb;return {start(){},stop(){}}}}}};vm.runInNewContext(readFileSync('miniprogram/pages/index/index.js','utf8'),{Page:p=>config=p,wx,require:p=>p.endsWith('camera-runtime.js')?{createDetector:async()=>{if(!detector)throw Error('not configured');return detector}}:require('../miniprogram/pages/index/'+p),Date,Math,console,setTimeout,clearTimeout});const p={...config,data:{...config.data},setData(update){Object.assign(this.data,update)}};config.__page=p;p.onLoad();return p}
test('WeChat button adapter counts damage and records button source',()=>{const p=page();p.start();p.hit();assert.equal(p.data.s.damage,10);assert.equal(p.data.s.rounds[0].source,'button')});
test('background pauses the round without counting another action',()=>{const p=page();p.start();p.hit();p.onHide();assert.equal(p.data.s.phase,'paused');assert.equal(p.data.s.totalActions,1);p.resume();assert.equal(p.data.s.phase,'active')});

test('stage clear can seal its round then enter next stage with a new round',()=>{const p=page();p.start();for(let i=0;i<4;i++)p.hit();p.end();p.advance();assert.equal(p.data.s.phase,'active');assert.equal(p.data.s.stage,1);assert.equal(p.data.s.rounds.length,2);assert.equal(p.data.v.roundActions,0)});
test('failed durable action has no attack feedback',()=>{const p=page();p.start();p.failWrites=true;p.hit();assert.equal(p.data.s.totalActions,0);assert.equal(p.data.fxDamage,0);assert.equal(p.data.blocked,true)});
test('page adapter exposes five states and sealed completion summary',()=>{const p=page();assert.equal(p.data.v.screen,'ready');p.start();assert.equal(p.data.v.screen,'battle');p.pause();assert.equal(p.data.v.screen,'rest');p.resume();for(let i=0;i<4;i++)p.hit();assert.equal(p.data.v.screen,'stageClear');while(p.data.s.phase!=='complete'){if(p.data.s.phase==='stageClear')p.advance();p.hit();}assert.equal(p.data.v.screen,'win');assert.equal(p.data.v.totalActions,18);assert.equal(p.data.v.roundDamage,180)});

test('camera round counts complete poses and cannot use the simulation button',async()=>{let now=0;const points=a=>{const rad=a*Math.PI/180;return [{name:'left_shoulder',x:100,y:100,score:1},{name:'left_elbow',x:100,y:200,score:1},{name:'left_wrist',x:100+100*Math.sin(rad),y:200-100*Math.cos(rad),score:1},{name:'left_hip',x:100,y:350,score:1}]};let angle=170;const p=page(false,{estimate:async()=>points(angle),dispose(){}});assert.equal(typeof p.startCamera,'function');await p.startCamera();assert.equal(p.data.s.rounds[0].source,'camera');p.hit();assert.equal(p.data.s.totalActions,0);await p.cameraReady();for(const a of [170,90,170]){angle=a;for(let i=0;i<3;i++){now+=150;await p.acceptFrame({width:4,height:4,data:new ArrayBuffer(64)},now)}}assert.equal(p.data.s.totalActions,1);assert.equal(p.data.s.damage,10);p.pause();p.onUnload()});
test('unconfigured model does not start a camera round',async()=>{const p=page();assert.equal(typeof p.startCamera,'function');await p.startCamera();assert.equal(p.data.s.rounds.length,0);assert.match(p.data.error,/not configured/)});
test('closing camera pauses active recognition and delayed poses cannot attack',async()=>{let resolve;const p=page(false,{estimate:()=>new Promise(r=>resolve=r),dispose(){}});assert.equal(typeof p.startCamera,'function');await p.startCamera();await p.cameraReady();const work=p.acceptFrame({width:1,height:1,data:new ArrayBuffer(4)},0);p.closeCamera();resolve([]);await work;assert.equal(p.data.s.phase,'paused');assert.equal(p.data.s.totalActions,0);p.onUnload()});

test('sealed camera stage can start a fresh camera round at the next stage',async()=>{const p=page(false,{estimate:async()=>[],dispose(){}});assert.equal(typeof p.startCamera,'function');await p.startCamera();let r=p.c.state.rounds[0];for(let i=0;i<4;i++)p.send({type:'action',eventId:'pose'+i,roundId:r.id,inputEpoch:p.c.state.inputEpoch,source:'camera',exerciseProfileId:'pushup.wall'});p.end();await p.startCamera();assert.equal(p.c.state.phase,'active');assert.equal(p.c.state.stage,1);assert.equal(p.c.state.rounds[1].source,'camera');p.onUnload()});
test('retrying a failed camera action preserves it but requires a deliberate resume',async()=>{const p=page(false,{estimate:async()=>[],dispose(){}});await p.startCamera();const r=p.c.state.rounds[0];p.failWrites=true;p.send({type:'action',eventId:'pose',roundId:r.id,inputEpoch:p.c.state.inputEpoch,source:'camera',exerciseProfileId:'pushup.wall'});p.failWrites=false;p.retry();assert.equal(p.c.state.totalActions,1);assert.equal(p.c.state.phase,'paused');p.onUnload()});
