import {createRun,getLevel,stageProfiles} from './lib/core.js';import {SnapshotStore,Coordinator} from './lib/storage.js';import {view,feedback,profileLabels} from './lib/ui.js';
const $=id=>document.getElementById(id);let c,atHome=false;const uid=()=>crypto.randomUUID();
function history(node,rounds){node.replaceChildren(...rounds.map(r=>{const e=document.createElement('div');e.className='history-row';for(const text of [`第 ${r.number} 轮`,`${r.actions} 次`,`贡献 ${r.damage}`]){const t=document.createElement('span');t.textContent=text;e.append(t)}return e}));if(!rounds.length)node.textContent='还没有记录，慢慢开始就好。'}
function render(){if(!c)return;const s=c.state,v=view(s);const profileStage=s.stage+(s.phase==='stageClear'?1:0);const profileKey=s.levelId+':'+profileStage;if($('profile').dataset.level!==profileKey){$('profile').dataset.level=profileKey;$('profile').replaceChildren(...stageProfiles(s.levelId,profileStage).map(p=>{const option=document.createElement('option');option.value=p;option.textContent=profileLabels[p];return option}))} $('exercise-hint').textContent=v.instruction+' 网页为按钮模拟；摄像头识别在微信真机测试。';$('scene').hidden=v.standing;$('standing-scene').hidden=!v.standing;$('standing-scene').className='standing-scene '+v.screen;$('standing-caption').textContent=v.stageName+' · '+v.damage+' / '+v.total;$('standing-steps').replaceChildren(...v.steps.map(step=>{const e=document.createElement('span');e.className='path-step '+(step.lit?'lit':'');e.textContent=step.lit?'✦':'·';return e}));$('overview').hidden=!atHome;$('level').hidden=atHome;try{const hearth=s.levelId==='hearth-01'?s:new SnapshotStore({get:k=>localStorage.getItem(k),set:(k,v)=>localStorage.setItem(k,v)}).load()||createRun('overview');$('overview-progress').textContent=`${hearth.damage} / ${hearth.initialShield} · ${hearth.totalActions} 次按钮模拟 · ${hearth.rounds.length} 轮`}catch{$('overview-progress').textContent='存档读取失败，请保留数据'};
 for(const screen of ['ready','battle','rest','stageClear','win'])$(screen).hidden=v.screen!==screen;
 $('title').textContent=({ready:v.gameTitle,battle:v.gameTitle,rest:'休息一下',stageClear:`阶段 ${v.stage} 完成`,win:v.gameTitle+'已点亮'})[v.screen];$('eyebrow').textContent=`${v.islandLabel} · ${v.stageName} · 阶段 ${v.stage} / 3`;$('subtitle').textContent=({ready:'先从你舒服的节奏开始。',battle:'一点点努力，微光正在汇聚。',rest:'暂停不会丢失进度。',stageClear:'准备好了，再继续下一阶段。',win:'每一轮努力，都留在这里。'})[v.screen];$('scene').className='game-art '+v.screen;
 $('round-actions').textContent=v.roundActions;$('round-damage').textContent=v.roundDamage;$('skills').textContent=v.skills;$('skill-note').textContent=v.skillLabel?`已选择${v.skillLabel}，下次动作触发。`:'每4次动作获得1份能量，最多2份。';document.querySelectorAll('.round-summary').forEach(e=>e.textContent=`本轮 ${v.roundActions} 次 · 贡献 ${v.roundDamage}`);
 $('stage-dots').replaceChildren(...[1,2,3].map(i=>{const e=document.createElement('span');e.className=i<=v.stage?'lit':'';e.textContent='✦';return e}));$('next-stage').textContent='下一阶段：'+v.nextStage+(v.standing?' · '+v.exerciseLabel+'，保持正面机位，准备好再继续。':'');$('end-stage').hidden=!v.activeRound;$('sealed-note').hidden=v.activeRound;
 $('win-summary').textContent=`总计 ${v.totalActions} 次 · ${v.roundCount} 轮完成`;history($('win-history'),v.rounds);history($('history'),v.rounds);
 $('progress').textContent=`${v.damage} / ${v.total}`;$('bar').max=v.total;$('bar').value=v.damage;$('total-note').textContent=`累计 ${v.totalActions} 次模拟动作 · ${v.roundCount} 轮`;$('status').textContent=c.blocked?'保存失败 · 已停止计数':'累计贡献';$('shield-hud').hidden=v.screen!=='battle';$('shield-hud').replaceChildren(...v.targets.map(t=>{const e=document.createElement('div');e.className='shield';const label=document.createElement('div');label.textContent=`${t.label} ${t.hp} / ${t.maxHp}`;const p=document.createElement('progress');p.max=t.maxHp;p.value=t.hp;e.append(label,p);return e}));
 $('save-failure').hidden=!c.blocked;document.querySelectorAll('button').forEach(b=>b.disabled=c.blocked&&!['retry','return','records','close-help','enter','enter-knee'].includes(b.id));$('focus').disabled=c.blocked||!v.skills;$('split').disabled=c.blocked||!v.skills;$('profile').disabled=c.blocked||v.activeRound;if(c.blocked)$('retry').focus();
}
function animate(fx){if(!fx.damage)return;const g=document.querySelector('.guardian');g.classList.remove('pulse');void g.offsetWidth;g.classList.add('pulse');const f=$('damage-fx');f.textContent='+'+fx.damage;f.classList.remove('play');void f.offsetWidth;f.classList.add('play');setTimeout(()=>f.classList.remove('play'),600)}
function dispatch(cmd){if(!c)return false;const before=c.state;try{c.dispatch(cmd);$('message').textContent='';render();animate(feedback(before,c.state));return true}catch(e){$('message').textContent=c.blocked?'保存失败，已停止计数。请保留页面并重试保存。':`操作未完成：${e.message}`;render();return false}}
function start(){return dispatch({type:'startRound',roundId:uid(),source:'button',exerciseProfileId:$('profile').value})}
try{c=new Coordinator(new SnapshotStore({get:k=>localStorage.getItem(k),set:(k,v)=>localStorage.setItem(k,v)}),createRun(uid()));render()}catch(e){$('message').textContent=`记录读取失败，请保留数据：${e.message}`;document.querySelectorAll('button,select').forEach(b=>b.disabled=true)}
$('start').onclick=start;for(const [id,type]of Object.entries({resume:'resume',pause:'pause',end:'endRound','end-stage':'endRound'}))$(id).onclick=()=>dispatch({type});
$('advance').onclick=()=>{const r=c.state.rounds.find(r=>r.id===c.state.currentRoundId);if(r&&!stageProfiles(c.state.levelId,c.state.stage+1).includes(r.exerciseProfileId)&&!dispatch({type:'endRound'}))return;if(!c.state.currentRoundId&&!start())return;dispatch({type:'advanceStage'})};
for(const skill of ['focus','split'])$(skill).onclick=()=>dispatch({type:'scheduleSkill',skill});
$('hit').onclick=()=>{const s=c.state,r=s.rounds.find(r=>r.id===s.currentRoundId);if(r)dispatch({type:'action',eventId:uid(),roundId:r.id,inputEpoch:s.inputEpoch,source:r.source,exerciseProfileId:r.exerciseProfileId})};
$('retry').onclick=()=>{const before=c.state;try{c.retry();$('message').textContent='已保存，可以继续。';render();animate(feedback(before,c.state))}catch{$('message').textContent='仍未保存，请保留页面稍后重试。';render()}};
const home=()=>{if(c?.state.phase==='active'&&!dispatch({type:'pause'}))return;atHome=true;render()};$('home').onclick=e=>{e.preventDefault();home()};$('return').onclick=home;function selectGame(id){if(c?.blocked)return;if(c?.state.phase==='active'&&!dispatch({type:'pause'}))return;try{const io={get:k=>localStorage.getItem(k),set:(k,v)=>localStorage.setItem(k,v)};c=new Coordinator(new SnapshotStore(io,id==='hearth-01'?'weiguang':'weiguang:'+id),createRun(uid(),getLevel(id)));atHome=false;render()}catch(e){$('message').textContent='记录读取失败，请保留数据：'+e.message}}$('enter').onclick=()=>selectGame('hearth-01');$('enter-knee').onclick=()=>selectGame('knee-01');$('records').onclick=()=>{$('history-panel').open=true;$('history-panel').scrollIntoView({behavior:'smooth'})};$('help').onclick=()=> $('instructions').showModal();$('close-help').onclick=()=> $('instructions').close();
document.addEventListener('visibilitychange',()=>{if(document.hidden&&c?.state.phase==='active'&&!c.blocked)dispatch({type:'pause'})});
